### PR TITLE
Update package.json to support svelte@next

### PR DESCRIPTION
**Pull request by Griizz**
## 📑 Description

Currently, this package cannot be installed with svelte@next. It works fine, but the dependency restriction is quite strict. I added svelte@next as a dependency to resolve this issue.

Current behavior when running `npm install` with svelte@next:
```
Found: svelte@5.0.0-next.165
npm ERR! node_modules/svelte
npm ERR!   dev svelte@"^5.0.0-next.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@"^5.0.0" from svelte-radix@2.0.0-next.1
```

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by shinokada** [comment]
This is already done at https://github.com/shinokada/svelte-radix/tree/svelte-5-runes.

https://svelte-radix.codewithshin.com/guide/svelte-5/getting-started

**Comment by Griizz** [comment]
Okay, so it depends on the package installer you use. So it's time for me to switch. ^^
`pnpm` ✔️  
`npm` ❌ 


Since I already collected this information, I will share it just in case. :)

> A ^ version range will not include pre-releases by default, unless the range itself includes a pre-release.

_Source: https://semver.org/_

You have to list `^5.0.0-next.1` explicitly for `npm`. Otherwise, you get the dependency issue.

You can reproduce the issue:

``` bash
# Setup a new project called "test" and select "Try the Svelte 5 preview (unstable!)"
$: npm create svelte@latest test
# change to the directory created
$: cd test
# run inital install
$: npm install
# try to install radix, which will fail
$: npm i -D svelte-lucide@next
```

**Comment by shinokada** [comment]
Use `pnpm`.
As you can see, I don't have any problems:

image

**Comment by Griizz** [comment]
Yeah, that's also what I found out. Already switched my project to `pnpm`. ^^
Just wanted to share the info. Thank you for your support. 👍

**Pull request closed without merging**
